# Generated by Django 3.2.7 on 2022-03-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
