# Generated by Django 3.1.3 on 2021-10-31 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cls', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField(default=1)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=30, null=True)),
                ('grade', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='attendance.grade')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceBook',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check', models.BooleanField(default=False)),
                ('period', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='attendance.period')),
                ('place', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
